---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: kube-system
spec:
  targetNamespace: kube-system
  path: ./kubernetes/apps/kube-system/cilium/app
  dependsOn:
    - name: cluster-apps
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: cilium
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cilium-bgp
#   namespace: flux-system
# spec:
#   targetNamespace: kube-system
#   path: ./kubernetes/apps/kube-system/cilium/bgp
#   dependsOn:
#     - name: cilium
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   prune: true
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
