---
clusterName: boondoggle
talosVersion: v1.9.2
kubernetesVersion: v1.32.0
endpoint: https://192.168.4.10:6443
allowSchedulingOnMasters: true
additionalMachineCertSans: []
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.245.0.0/16
cniConfig:
  name: none
nodes:
  - &node
    hostname: cp0
    ipAddress: 192.168.4.10
    controlPlane: true
    installDisk: /dev/sdb
    machineSpec:
      mode: metal
      arch: amd64
    talosImageURL: ghcr.io/siderolabs/installer
  - << : *node
    hostname: cp1
    ipAddress: 192.168.4.11
  - << : *node
    hostname: cp2
    ipAddress: 192.168.4.12
controlPlane:
  patches:
    - |-
      cluster:
        extraManifests:
          - # renovate: datasource=github-releases depName=kubernetes-sigs/gateway-api
            https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/experimental-install.yaml
          - # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
            https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.81.0/stripped-down-crds.yaml
          - # renovate: datasource=github-releases depName=k8snetworkplumbingwg/network-attachment-definition-client
            https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/raw/refs/tags/v1.7.5/artifacts/networks-crd.yaml
    # Disable search domain everywhere
    - |-
      machine:
        network:
          disableSearchDomain: true

    # Disable Host DNS
    # https://www.talos.dev/v1.9/reference/configuration/v1alpha1/config/#Config.machine.features.hostDNS
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
    # Enable KubePrism
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445

    - |-
      cluster:
        discovery:
          enabled: true
          registries:
            kubernetes:
              disabled: true
            service:
              disabled: false
    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true
        proxy:
          disabled: true
        coreDNS:
          disabled: true
    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - kube-system


    # Configure containerd
    - &containerdPatch |-
      machine:
        files: # keep
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |-
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false
    - &sysctlPatch |-
      machine:
        sysctls: # keep
          fs.inotify.max_user_watches: 1048576
          fs.inotify.max_user_instances: 8192
          kernel.randomize_va_space: 0
          net.core.netdev_max_backlog: 30000
          net.core.rmem_max: 67108864
          net.core.wmem_max: 67108864
          net.ipv4.tcp_rmem: 4096 87380 33554432
          net.ipv4.tcp_wmem: 4096 65536 33554432
          net.ipv4.tcp_tw_reuse: 1
          net.ipv4.tcp_window_scaling: 1
    # Kubelet configuration
    - &kubeletPatch |-
      machine:
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true
            rotate-server-certificates: "true"
          extraConfig:
            maxPods: 150
          nodeIP: # keep this
            validSubnets:
                - 192.168.4.0/24
    # Configure cluster loopback
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - ${clusterName}.boondoggle.dev
    # ETCD configuration
    - |-
      cluster:
        etcd:
          advertisedSubnets:
            - 192.168.4.0/24
    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl