---
version: "3"
# https://developer.1password.com/docs/connect/get-started/?deploy=kubernetes&method=1password-com
tasks:
  connect:
    desc: Create new 1Password connect token named {{ .OP_CONNECT_TOKEN }} on server named {{ .OP_CONNECT_SERVER }}
    prompt: Create new 1Password connect token named {{ .OP_CONNECT_TOKEN }} on server named {{ .OP_CONNECT_SERVER }}?
    deps:
      - connect_server
    status:
      - op connect token list --format json | jq --exit-status '.[] | select(.name=="{{ .OP_CONNECT_TOKEN }}")'
    cmds:
      - token=$(op connect token create {{ .OP_CONNECT_TOKEN }} --server {{ .OP_CONNECT_SERVER }} --vault {{ .OP_VAULT }}) && op item create --vault {{ .OP_VAULT }} --category "API Credential" --title {{.OP_CONNECT_TOKEN}} "credential=$token"
    preconditions:
      - op user get --me
      - op vault list --format=json | jq --exit-status '.[] | select(.name=="{{ .OP_VAULT }}")'
      - op connect server get {{ .OP_CONNECT_SERVER }}
  connect_server:
    desc: Create new 1Password connect server named {{ .OP_CONNECT_SERVER }}
    prompt: Create new 1Password connect server named {{ .OP_CONNECT_SERVER }}?
    internal: true
    status:
      - op connect server get {{ .OP_CONNECT_SERVER }}
      - op document get {{ .OP_CONNECT_CREDENTIALS_NAME }} --vault {{ .OP_VAULT }} > /dev/null
    cmds:
      - op connect server create {{ .OP_CONNECT_SERVER }} --vaults {{ .OP_VAULT }}
      - cat 1password-credentials.json | op document create --vault {{ .OP_VAULT }} --file-name 1password-credentials.json --title {{ .OP_CONNECT_CREDENTIALS_NAME }}
    preconditions:
      - op user get --me
      - op vault list --format=json | jq --exit-status '.[] | select(.name=="{{ .OP_VAULT }}")'
