---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-token-secret
    creationPolicy: Owner
    template:
      data:
        token: op://Personal/FLUX_GITHUB_TOKEN/Section_nduyrgmwlnt3ljwrkibrvxpace/token
  dataFrom:
    - extract:
        key: github
