---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github
spec:
  type: github
  address: https://github.com/grahamcrowell/home-cluster
  secretRef:
    name: github-pat
